### ISSUE TITLE
Portability issues when including in the Lazyman Neovim configuration manager

### ISSUE THREAD

**Issue by doctorfree** [b0o/dotfiles#2]
I've included this Neovim configuration in the [Lazyman Neovim Configuration Manager](https://github.com/doctorfree/nvim-lazyman). It works well and this is not necessarily an issue, more of an FYI or an RFC.

The `lazyman` command installs this configuration in `~/.config/nvim-Maddison` and applies [a patch](https://github.com/doctorfree/nvim-lazyman/blob/main/scripts/patches/nvim-Maddison.patch) to comment out the use of `codegpt` including keymaps and statusline entry. This is because it requires a private key. In addition, the patch modifies some provider settings that were referencing `asdf` paths. The patching is minor and the resulting config performs well.

I really like your Neovim configuration look and feel. I will probably be stealing some of your work for my own :1st_place_medal: 

Here is the [Lazyman description of this config](https://github.com/doctorfree/nvim-lazyman/blob/main/info/Maddison.md). Let me know if you have any suggestions, comments, corrections, or anything regarding the inclusion of your Neovim configuration in `Lazyman`. Thanks, it's a really nice config.

**Comment by b0o** [comment]
That’s awesome, thank you for including my config in your project, and thank you for the kind words! 

I love the idea behind your project, I’m going to try out some of those configs as soon as I have time.
